typography_spectrum: 0.49685
color:
  brandColors:
    - '#151515'
    - '#637db7'
    - '#96abd5'
    - '#dad9e1'
    - '#52413d'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23945
analytics:
  google: null
  facebook: null
  twitter: null
name: Sydney Wollongong 2016
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Opera house
    id: 7aeb0d59-fc2b-49fc-9340-cde2629a0a9c
    type: content
favicon: null
title: Sydney
description: May 2016
purpose: []
