name: Sydney Wollongong 2016
favicon: null
layout_spectrum: 0.13745057443156838
typography_spectrum: 0.08695348422043025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6485977387055755
  lightness: 0.10320627712644637
  saturation: 0.7877218017820269
  rhythmicContrast: 0.6150551228784025
purpose: []
