name: Sydney Wollongong 2016
favicon: null
layout_spectrum: 0.23945
typography_spectrum: 0.49685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#637db7'
    - '#96abd5'
    - '#dad9e1'
    - '#52413d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
